apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-container
        image: eric096/django-api-gym:1
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: secret-django

