apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gym-api-django-ingress
spec:
  rules:
  - host: api.localhost.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: svc-django
            port:
              number: 8000