name: CI/CD pipeline

#Especifica os eventos que disparam o workflow
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    #Especifica que o job deve ser executado em uma máquina virtual com o sistema operacional Ubuntu na versão mais recente.
    runs-on: ubuntu-latest
    steps:
    - name: Checando o código
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        . venv/bin/activate
        python manage.py test

    - name: Hadolint test
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        config: .hadolint.yml
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.20.0
      with: 
        severity: 'CRITICAL, HIGH, MEDIUM'
        format: 'table'
        image-ref: docker.io/eric096/gym-api:1.0

    - name: Install Trivy
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.56.1/trivy_0.56.1_Linux-64bit.tar.gz
        tar -zxvf trivy_0.56.1_Linux-64bit.tar.gz 
        mv trivy /usr/local/bin

    - name: Run Trivy vulnerability scanner:2.0
      run: |
        trivy image --scanners vuln,secret,misconfig --severity HIGH,CRITICAL docker.io/eric096/gym-api-verify:1.0


    