name: CI/CD pipeline

#Especifica os eventos que disparam o workflow
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    #Especifica que o job deve ser executado em uma máquina virtual com o sistema operacional Ubuntu na versão mais recente.
    runs-on: ubuntu-latest
    steps:
    - name: Checando o código
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        . venv/bin/activate
        python manage.py test

    - name: Hadolint test
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        config: .hadolint.yml

    - name: Install Trivy
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.56.1/trivy_0.56.1_Linux-64bit.tar.gz
        tar -zxvf trivy_0.56.1_Linux-64bit.tar.gz 
        mv trivy /usr/local/bin

    - name: Run Trivy vulnerability scanner:2.0
      run: |
        trivy fs --scanners vuln,secret,misconfig --severity HIGH,CRITICAL Dockerfile

    - name: Set up Docker build
      uses: docker/setup-buildx-action@v3
      
    - name: Build image Docker
      run: |
        docker build -t ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:latest .

    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push image Dockerhub
      if: ${{ success() }}
      run: |
        docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:latest
      



    